version: '3.8'

# Volúmenes compartidos para datos persistentes
volumes:
  printer_data:
  gcode_files:
  database:


services:
  klipper:
    image: mkuf/klipper:latest # Imagen confiable encontrada en Docker Hub
    container_name: klipper
    restart: unless-stopped
    privileged: true # Necesario para acceder al hardware USB
    volumes:
      - printer_data:/opt/printer_data
      - gcode_files:/opt/gcode_files
      - /dev:/dev # Acceso a dispositivos USB
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # Ajustar según el puerto USB de tu impresora
    networks:
      - klipper_network

  moonraker:
    image: mkuf/moonraker:latest # Imagen confiable encontrada en Docker Hub
    container_name: moonraker
    restart: unless-stopped
    depends_on:
      - klipper
    volumes:
      - printer_data:/opt/printer_data:rw
      - gcode_files:/opt/gcode_files:rw
      - database:/opt/printer_data/database
    ports:
      - "7125:7125" # Puerto para la API REST
    environment:
      - ENABLE_CORS=true
    networks:
      - klipper_network

  mainsail:
    image: dimalo/mainsail:latest # Imagen confiable encontrada en Docker Hub
    container_name: mainsail
    restart: unless-stopped
    depends_on:
      - moonraker
    ports:
      - "80:80" # Puerto para la interfaz web
    volumes:
      - printer_data:/opt/printer_data:ro
      - gcode_files:/opt/gcode_files:ro
    networks:
      - klipper_network

networks:
  klipper_network:
    driver: bridge
